//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autodraw.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Autodraw.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DFS.
        /// </summary>
        public static string AlgorithmDFS {
            get {
                return ResourceManager.GetString("AlgorithmDFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge-Following.
        /// </summary>
        public static string AlgorithmEdgeTraversal {
            get {
                return ResourceManager.GetString("AlgorithmEdgeTraversal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Version: C# 10.0.
        /// </summary>
        public static string AutoDrawLanguageVersion {
            get {
                return ResourceManager.GetString("AutoDrawLanguageVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework Version: net6.0.
        /// </summary>
        public static string AutoDrawNetFramework {
            get {
                return ResourceManager.GetString("AutoDrawNetFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoDraw Open Beta.
        /// </summary>
        public static string AutoDrawTitle {
            get {
                return ResourceManager.GetString("AutoDrawTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v2.2b.
        /// </summary>
        public static string AutoDrawVersion {
            get {
                return ResourceManager.GetString("AutoDrawVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Version: v2.2.0.
        /// </summary>
        public static string AutoDrawVersionDetailed {
            get {
                return ResourceManager.GetString("AutoDrawVersionDetailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin Drawing.
        /// </summary>
        public static string BeginDraw {
            get {
                return ResourceManager.GetString("BeginDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border (Semi-Shader).
        /// </summary>
        public static string BSS {
            get {
                return ResourceManager.GetString("BSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Config.
        /// </summary>
        public static string ConfigLoad {
            get {
                return ResourceManager.GetString("ConfigLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Config.
        /// </summary>
        public static string ConfigSelected {
            get {
                return ResourceManager.GetString("ConfigSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crosshatch.
        /// </summary>
        public static string Crosshatch {
            get {
                return ResourceManager.GetString("Crosshatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagonal Crosshatch.
        /// </summary>
        public static string Dcrosshatch {
            get {
                return ResourceManager.GetString("Dcrosshatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erosion (Shader).
        /// </summary>
        public static string ES {
            get {
                return ResourceManager.GetString("ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Draw Bypass.
        /// </summary>
        public static string FDBypass {
            get {
                return ResourceManager.GetString("FDBypass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string FileNew {
            get {
                return ResourceManager.GetString("FileNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string FileOpen {
            get {
                return ResourceManager.GetString("FileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string FileSave {
            get {
                return ResourceManager.GetString("FileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experimental Filters.
        /// </summary>
        public static string FiltersExperimental {
            get {
                return ResourceManager.GetString("FiltersExperimental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Filters.
        /// </summary>
        public static string FiltersGeneral {
            get {
                return ResourceManager.GetString("FiltersGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern Filters.
        /// </summary>
        public static string FiltersPattern {
            get {
                return ResourceManager.GetString("FiltersPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha Threshold.
        /// </summary>
        public static string GeneralAlphaThreshold {
            get {
                return ResourceManager.GetString("GeneralAlphaThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Delay.
        /// </summary>
        public static string GeneralClickDelay {
            get {
                return ResourceManager.GetString("GeneralClickDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Algorithm.
        /// </summary>
        public static string GeneralDrawAlgorithm {
            get {
                return ResourceManager.GetString("GeneralDrawAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is incomplete, some functions here may not work..
        /// </summary>
        public static string GeneralInfo1 {
            get {
                return ResourceManager.GetString("GeneralInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval.
        /// </summary>
        public static string GeneralInterval {
            get {
                return ResourceManager.GetString("GeneralInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luminance Threshold.
        /// </summary>
        public static string GeneralLuminanceThreshold {
            get {
                return ResourceManager.GetString("GeneralLuminanceThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate Mouse Control (Buggy).
        /// </summary>
        public static string GeneralSwitch1 {
            get {
                return ResourceManager.GetString("GeneralSwitch1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Finished Drawing Popup.
        /// </summary>
        public static string GeneralSwitch2 {
            get {
                return ResourceManager.GetString("GeneralSwitch2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Log files.
        /// </summary>
        public static string GeneralSwitch3 {
            get {
                return ResourceManager.GetString("GeneralSwitch3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Skip Rescan.
        /// </summary>
        public static string GeneralSwitch4 {
            get {
                return ResourceManager.GetString("GeneralSwitch4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inline Border (Semi-Shader).
        /// </summary>
        public static string InlineBorderShader {
            get {
                return ResourceManager.GetString("InlineBorderShader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inline (Shader).
        /// </summary>
        public static string InlineShader {
            get {
                return ResourceManager.GetString("InlineShader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert.
        /// </summary>
        public static string Invert {
            get {
                return ResourceManager.GetString("Invert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string MainTab1 {
            get {
                return ResourceManager.GetString("MainTab1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string MainTab2 {
            get {
                return ResourceManager.GetString("MainTab2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configs.
        /// </summary>
        public static string MainTab3 {
            get {
                return ResourceManager.GetString("MainTab3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string MainTab4 {
            get {
                return ResourceManager.GetString("MainTab4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        public static string Maximum {
            get {
                return ResourceManager.GetString("Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        public static string Minimum {
            get {
                return ResourceManager.GetString("Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenAI API Key.
        /// </summary>
        public static string OpenAPIKey {
            get {
                return ResourceManager.GetString("OpenAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline.
        /// </summary>
        public static string Outline {
            get {
                return ResourceManager.GetString("Outline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline (Shader).
        /// </summary>
        public static string OutlineShader {
            get {
                return ResourceManager.GetString("OutlineShader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Image.
        /// </summary>
        public static string ProcessIMG {
            get {
                return ResourceManager.GetString("ProcessIMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may want to report this to the developers..
        /// </summary>
        public static string ReportDev {
            get {
                return ResourceManager.GetString("ReportDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        public static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your language.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string SettingsTab1 {
            get {
                return ResourceManager.GetString("SettingsTab1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes.
        /// </summary>
        public static string SettingsTab2 {
            get {
                return ResourceManager.GetString("SettingsTab2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        public static string SettingsTab3 {
            get {
                return ResourceManager.GetString("SettingsTab3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketplace.
        /// </summary>
        public static string SettingsTab4 {
            get {
                return ResourceManager.GetString("SettingsTab4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dev. Options.
        /// </summary>
        public static string SettingsTab5 {
            get {
                return ResourceManager.GetString("SettingsTab5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Stripes.
        /// </summary>
        public static string StripesHorizontal {
            get {
                return ResourceManager.GetString("StripesHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Stripes.
        /// </summary>
        public static string StripesVertical {
            get {
                return ResourceManager.GetString("StripesVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark theme?.
        /// </summary>
        public static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Theme.
        /// </summary>
        public static string ThemeLoad {
            get {
                return ResourceManager.GetString("ThemeLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark/Light.
        /// </summary>
        public static string ThemeToggle {
            get {
                return ResourceManager.GetString("ThemeToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the delay (in ms) which AutoDraw will wait in-between each image chunk..
        /// </summary>
        public static string ToolTipDelay {
            get {
                return ResourceManager.GetString("ToolTipDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the speed at which the image will be drawn. One interval equates to 100 nanoseconds.
        /// </summary>
        public static string ToolTipSpeed {
            get {
                return ResourceManager.GetString("ToolTipSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This decides what portions of the image will be drawn, based on if it falls within the threshold. Threshold is based on 0-255.
        /// </summary>
        public static string ToolTipThreshold {
            get {
                return ResourceManager.GetString("ToolTipThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Aspect Ratio.
        /// </summary>
        public static string UnlockAspectRatio {
            get {
                return ResourceManager.GetString("UnlockAspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string WordLanguage {
            get {
                return ResourceManager.GetString("WordLanguage", resourceCulture);
            }
        }
    }
}
